### ISSUE TITLE
How turn on?

### ISSUE THREAD

**Issue by vinilaraa** [sergio11/teVeo#1]
How make this works??

**Comment by thebestclass** [comment]
Hola estoy aquí
VM208:132 Creando entorno .....
VM208:101 Descargando Servicios .....
VM208:107 Servicio : DependencesManager cargado
VM208:107 Servicio : TemplateManager cargado
VM208:107 Servicio : ModuleManager cargado
VM208:107 Servicio : SessionManager cargado
VM208:107 Servicio : ActivityManager cargado
VM208:107 Servicio : HistoryManager cargado
VM211:74 Componentes a instanciar....
VM211:75 Object {templateManager: Object, moduleManager: Object, sessionManager: Object, activityManager: Object, historyManager: Object}
VM211:78 Cargando Componente : TemplateManager
VM211:78 Cargando Componente : ModuleManager
VM211:78 Cargando Componente : SessionManager
VM211:78 Cargando Componente : ActivityManager
VM211:78 Cargando Componente : HistoryManager
VM208:145 Estos son los servicios
VM208:146 Object {DEPENDENCES_MANAGER: Object, TEMPLATE_MANAGER: Object, MODULE_MANAGER: Object, SESSION_MANAGER: Object, ACTIVITY_MANAGER: Object…}
VM223:67 Uncaught ReferenceError: templating is not definedActivityManager.startActivity @ VM223:67(anonymous function) @ app.js:44x.Callbacks.c @ jquery-1.10.2.min.js:4x.Callbacks.p.fireWith @ jquery-1.10.2.min.js:4x.extend.Deferred.x.each.i.(anonymous function) @ jquery-1.10.2.min.js:4(anonymous function) @ VM208:147x.Callbacks.c @ jquery-1.10.2.min.js:4x.Callbacks.p.fireWith @ jquery-1.10.2.min.js:4x.extend.Deferred.x.each.i.(anonymous function) @ jquery-1.10.2.min.js:4(anonymous function) @ VM208:111x.Callbacks.c @ jquery-1.10.2.min.js:4x.Callbacks.p.fireWith @ jquery-1.10.2.min.js:4k @ jquery-1.10.2.min.js:6x.ajaxTransport.n.send.r @ jquery-1.10.2.min.js:6

**Comment by sergio11** [comment]
I feel it is not yet finished , is a personal project that will use WebSockets , WebRTC , WebNotifications and IndexedDB

**Comment by thebestclass** [comment]
I loved the project, it must extract the WebRTC, could provide the db or give me a direction?
